// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9-10-2024, 20:37:56
const configMerger = require("/home/LorenzovandenDungen/nuxt_yelp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{"colors":{"yelp-red":"#d32323"}}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/LorenzovandenDungen/nuxt_yelp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/LorenzovandenDungen/nuxt_yelp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/LorenzovandenDungen/nuxt_yelp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/LorenzovandenDungen/nuxt_yelp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/LorenzovandenDungen/nuxt_yelp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/LorenzovandenDungen/nuxt_yelp/plugins/**/*.{js,ts,mjs}","/home/LorenzovandenDungen/nuxt_yelp/composables/**/*.{js,ts,mjs}","/home/LorenzovandenDungen/nuxt_yelp/utils/**/*.{js,ts,mjs}","/home/LorenzovandenDungen/nuxt_yelp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/LorenzovandenDungen/nuxt_yelp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/LorenzovandenDungen/nuxt_yelp/app.config.{js,ts,mjs}"] }));

module.exports = config
